const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "REST API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "List",
            "description": "Endpoints"
        },
        {
            "name": "Task",
            "description": "Endpoints"
        }
    ],
    definitions: {
        ListCreateRequest: {
            name: "Test list"
        },
        ListCreateResponse: {
            id: "62761de75ff85e389c886d6b", 
            success: true, 
            error: "" 
        },
        ListDeleteRequest: {
            id: "62761de75ff85e389c886d6b"
        },
        ListDeleteResponse: {
            id: "62761de75ff85e389c886d6b", 
            success: true, 
            error: "" 
        },
        ListGetResponse: {
            lists: [
                {
                    _id: "62761de75ff85e389c886d6b", 
                    name: "Test List", 
                    createdAt: "2022-05-28T07:20:22.000Z",
                    updatedAt: "2022-05-28T07:20:22.000Z"
                }
            ], 
            success: true, 
            error: "" 
        },
        ListFindResponse: {
            lists: [
                {
                    _id: "62761de75ff85e389c886d6b", 
                    name: "Test List"
                }
            ], 
            success: true, 
            error: "" 
        },
        TaskCreateRequest: {
            listId: "62761de75ff85e389c886d6b",
            name: "Test task",
            description: "Test task description",
            deadline: "2022-05-28T07:20:22.000Z"
        },
        TaskCreateResponse: {
            id: "62761fe15ff85e389c886d6c", 
            success: true, 
            error: "" 
        },
        TaskUpdateRequest: {
            id: "62761fe15ff85e389c886d6c",
            name: "Test task",
            description: "Test task description",
            deadline: "2022-05-28T07:20:22.000Z"
        },
        TaskUpdateResponse: {
            success: true, 
            error: "" 
        },
        TasksMoveRequest: {
            ids: [
                "62761fe15ff85e389c886d6c"
            ],
            listId: "62761de75ff85e389c886d6b"
        },
        TasksMoveResponse: {
            ids: [
                "62761fe15ff85e389c886d6c"
            ],
            success: true, 
            error: "" 
        },
        TaskCompleteResponse: {
            id: "62761fe15ff85e389c886d6c",
            success: true, 
            error: "" 
        },
        TaskDeleteResponse: {
            id: "62761fe15ff85e389c886d6c",
            success: true, 
            error: "" 
        },
        TasksDeleteRequest: {
            ids: [
                "62761fe15ff85e389c886d6c"
            ]
        },
        TasksDeleteResponse: {
            ids: [
                "62761fe15ff85e389c886d6c"
            ],
            success: true, 
            error: "" 
        },
        TasksGetResponse: {
            tasks: [
                {
                    
                    _id: "62761fe15ff85e389c886d6c", 
                    name: "Test task", 
                    description: "Test task description",
                    deadline: "2022-05-28T07:20:22.000Z",
                    completed: false,
                    createdAt: "2022-05-28T07:20:22.000Z",
                    updatedAt: "2022-05-28T07:20:22.000Z"
                }
            ],
            success: true, 
            error: "" 
        },
        TaskGetResponse: {
            task: {
                _id: "62761fe15ff85e389c886d6c", 
                listId: "62761de75ff85e389c886d6b", 
                name: "Test task", 
                description: "Test task description",
                deadline: "2022-05-28T07:20:22.000Z",
                completed: false,
                createdAt: "2022-05-28T07:20:22.000Z",
                updatedAt: "2022-05-28T07:20:22.000Z"
            },
            success: true, 
            error: "" 
        }
    }
}

const outputFile = './data/swagger-output.json'
const endpointsFiles = ['./routes/index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})